forge "http://forge.puppetlabs.com"

# official puppetlabs modules
mod 'puppetlabs/apt', '2.1.1'
mod 'puppetlabs/concat', '1.2.4'
mod 'puppetlabs/stdlib', '4.8.0'
mod 'puppetlabs/postgresql', '4.6.0'

# configs module
mod 'andrekeller/configs',
  :git => 'https://github.com/andrekeller/puppet-configs.git'
